use serde::Serialize;
use std::{fs, path::{Path, PathBuf}, time::Duration};
use tauri::State;
use crate::{run_bounded, workspace_root, CommandResult, WorkspaceState};

#[derive(Serialize)] #[serde(rename_all="camelCase")] pub struct GitBranch { name:String,current:bool,upstream:Option<String> }
#[derive(Serialize)] #[serde(rename_all="camelCase")] pub struct GitCommitSummary { sha:String,author:String,timestamp:i64,subject:String }
#[derive(Serialize)] #[serde(rename_all="camelCase")] pub struct GitRemote { name:String,fetch_url:String,push_url:String }

#[tauri::command] pub fn git_fetch(state:State<'_,WorkspaceState>)->Result<CommandResult,String>{run_bounded(&workspace_root(&state)?,"git",&["fetch".into(),"--prune".into()],Duration::from_secs(120))}
#[tauri::command] pub fn git_pull(state:State<'_,WorkspaceState>)->Result<CommandResult,String>{run_bounded(&workspace_root(&state)?,"git",&["pull".into(),"--ff-only".into()],Duration::from_secs(120))}
#[tauri::command] pub fn git_push(state:State<'_,WorkspaceState>)->Result<CommandResult,String>{run_bounded(&workspace_root(&state)?,"git",&["push".into()],Duration::from_secs(120))}
#[tauri::command] pub fn git_branches(state:State<'_,WorkspaceState>)->Result<Vec<GitBranch>,String>{let result=run_bounded(&workspace_root(&state)?,"git",&["for-each-ref".into(),"--format=%(refname:short)%09%(HEAD)%09%(upstream:short)".into(),"refs/heads".into()],Duration::from_secs(15))?;if !result.ok{return Err(nonempty(&result.stderr,"Git branch listing failed"))}let mut branches=result.stdout.lines().filter_map(|line|{let mut fields=line.split('\t');let name=fields.next()?.trim().to_string();if name.is_empty(){return None}let current=fields.next().map(|v|v.trim()=="*").unwrap_or(false);let upstream=fields.next().map(str::trim).filter(|v|!v.is_empty()).map(str::to_string);Some(GitBranch{name,current,upstream})}).collect::<Vec<_>>();branches.sort_by(|a,b|b.current.cmp(&a.current).then_with(||a.name.cmp(&b.name)));Ok(branches)}
#[tauri::command] pub fn git_switch_branch(name:String,state:State<'_,WorkspaceState>)->Result<CommandResult,String>{validate_ref_name(&name)?;run_bounded(&workspace_root(&state)?,"git",&["switch".into(),name],Duration::from_secs(30))}
#[tauri::command] pub fn git_create_branch(name:String,state:State<'_,WorkspaceState>)->Result<CommandResult,String>{validate_ref_name(&name)?;run_bounded(&workspace_root(&state)?,"git",&["switch".into(),"-c".into(),name],Duration::from_secs(30))}
#[tauri::command] pub fn git_merge(name:String,state:State<'_,WorkspaceState>)->Result<CommandResult,String>{validate_ref_name(&name)?;run_bounded(&workspace_root(&state)?,"git",&["merge".into(),"--no-edit".into(),name],Duration::from_secs(120))}
#[tauri::command] pub fn git_rebase(name:String,state:State<'_,WorkspaceState>)->Result<CommandResult,String>{validate_ref_name(&name)?;run_bounded(&workspace_root(&state)?,"git",&["rebase".into(),name],Duration::from_secs(120))}
#[tauri::command] pub fn git_stash_push(message:Option<String>,state:State<'_,WorkspaceState>)->Result<CommandResult,String>{let mut args=vec!["stash".into(),"push".into(),"--include-untracked".into()];if let Some(m)=message{let m=m.trim();if m.is_empty()||m.len()>512{return Err("stash message must be 1-512 characters".into())}args.extend(["-m".into(),m.into()]);}run_bounded(&workspace_root(&state)?,"git",&args,Duration::from_secs(60))}
#[tauri::command] pub fn git_stash_pop(state:State<'_,WorkspaceState>)->Result<CommandResult,String>{run_bounded(&workspace_root(&state)?,"git",&["stash".into(),"pop".into()],Duration::from_secs(60))}
#[tauri::command] pub fn git_tag(name:String,state:State<'_,WorkspaceState>)->Result<CommandResult,String>{validate_ref_name(&name)?;run_bounded(&workspace_root(&state)?,"git",&["tag".into(),name],Duration::from_secs(30))}
#[tauri::command] pub fn git_remotes(state:State<'_,WorkspaceState>)->Result<Vec<GitRemote>,String>{let root=workspace_root(&state)?;let names=run_bounded(&root,"git",&["remote".into()],Duration::from_secs(10))?;if !names.ok{return Err(nonempty(&names.stderr,"Git remotes unavailable"))}let mut out=Vec::new();for name in names.stdout.lines().map(str::trim).filter(|v|!v.is_empty()){let fetch=run_bounded(&root,"git",&["remote".into(),"get-url".into(),name.into()],Duration::from_secs(10))?;let push=run_bounded(&root,"git",&["remote".into(),"get-url".into(),"--push".into(),name.into()],Duration::from_secs(10))?;out.push(GitRemote{name:name.into(),fetch_url:fetch.stdout.trim().into(),push_url:push.stdout.trim().into()});}Ok(out)}
#[tauri::command] pub fn git_history(limit:Option<usize>,state:State<'_,WorkspaceState>)->Result<Vec<GitCommitSummary>,String>{let limit=limit.unwrap_or(100).clamp(1,500);let result=run_bounded(&workspace_root(&state)?,"git",&["log".into(),format!("-{limit}"),"--date-order".into(),"--pretty=format:%H%x09%an%x09%at%x09%s".into()],Duration::from_secs(20))?;if !result.ok{return Err(nonempty(&result.stderr,"Git history unavailable"))}Ok(result.stdout.lines().filter_map(|line|{let mut f=line.splitn(4,'\t');Some(GitCommitSummary{sha:f.next()?.into(),author:f.next()?.into(),timestamp:f.next()?.parse().ok()?,subject:f.next().unwrap_or("").into()})}).collect())}
#[tauri::command] pub fn git_clone_repository(url:String,parent:String,directory:Option<String>)->Result<String,String>{validate_repository_url(&url)?;let parent=fs::canonicalize(parent).map_err(|e|format!("clone destination unavailable: {e}"))?;if !parent.is_dir(){return Err("clone destination must be a directory".into())}let directory=directory.map(|v|validate_directory_name(&v).map(|_|v)).transpose()?;let mut args=vec!["clone".into(),"--".into(),url];if let Some(name)=&directory{args.push(name.clone())}let result=run_bounded(&parent,"git",&args,Duration::from_secs(300))?;if !result.ok{return Err(nonempty(&result.stderr,"Git clone failed"))}let target=match directory{Some(name)=>parent.join(name),None=>infer_clone_target(&parent,&args[2])?};Ok(fs::canonicalize(target).map_err(|e|format!("cloned repository unavailable: {e}"))?.to_string_lossy().to_string())}
fn validate_ref_name(value:&str)->Result<(),String>{let value=value.trim();if value.is_empty()||value.len()>255||value.starts_with('-')||value.contains("..")||value.contains("@{")||value.ends_with('.')||value.ends_with('/')||value.chars().any(|ch|ch.is_control()||matches!(ch,' '|'~'|'^'|':'|'?'|'*'|'['|'\\')){return Err("invalid Git ref name".into())}Ok(())}
fn validate_repository_url(value:&str)->Result<(),String>{let value=value.trim();if value.len()<5||value.len()>4096{return Err("invalid Git repository URL".into())}let allowed=value.starts_with("https://")||value.starts_with("ssh://")||value.starts_with("git@")||value.starts_with("file://");if !allowed||value.contains('\n')||value.contains('\r'){return Err("Git repository URL must use HTTPS, SSH, or an explicit file URL".into())}Ok(())}
fn validate_directory_name(value:&str)->Result<(),String>{let value=value.trim();if value.is_empty()||value.len()>255||value=="."||value==".."||value.contains('/')||value.contains('\\')||value.chars().any(char::is_control){return Err("invalid clone directory name".into())}Ok(())}
fn infer_clone_target(parent:&Path,url:&str)->Result<PathBuf,String>{let trimmed=url.trim_end_matches('/');let tail=trimmed.rsplit(['/',':']).next().unwrap_or("").trim_end_matches(".git");validate_directory_name(tail)?;Ok(parent.join(tail))}
fn nonempty(value:&str,fallback:&str)->String{let trimmed=value.trim();if trimmed.is_empty(){fallback.into()}else{trimmed.into()}}
