import * as monaco from 'monaco-editor';
import { invoke } from '@tauri-apps/api/core';
import { open, save } from '@tauri-apps/plugin-dialog';
import { Terminal } from '@xterm/xterm';
import { FitAddon } from '@xterm/addon-fit';
import './vscode-freedom.css';

const api=()=>window.CortexWorkbench;const state={untitled:0,activeUntitled:null,splitEditor:null,terminals:[],activeTerminal:null};const commands=new Map();const $=s=>document.querySelector(s);const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function notifications(){let h=$('#cortex-notifications');if(!h){h=document.createElement('div');h.id='cortex-notifications';document.body.append(h);}return h}function notify(message,kind='info'){const i=document.createElement('div');i.className=`cortex-notification ${kind}`;i.textContent=message;const x=document.createElement('button');x.textContent='×';x.onclick=()=>i.remove();i.append(x);notifications().append(i);setTimeout(()=>i.remove(),8000)}
function register(id,label,run,when=()=>true){commands.set(id,{id,label,run,when})}function installPalette(){document.querySelector('#command-palette')?.remove();const p=document.createElement('div');p.id='command-palette';p.className='cortex-quick-pick';p.hidden=true;p.innerHTML='<input aria-label="Command Palette" placeholder="> Type a command"><div class="quick-results"></div>';document.body.append(p);const input=p.querySelector('input');const render=()=>{const q=input.value.replace(/^>/,'').trim().toLowerCase(),out=p.querySelector('.quick-results');out.replaceChildren();for(const c of [...commands.values()].filter(c=>c.when()&&(`${c.label} ${c.id}`).toLowerCase().includes(q)).slice(0,100)){const b=document.createElement('button');b.innerHTML=`<span>${esc(c.label)}</span><small>${esc(c.id)}</small>`;b.onclick=async()=>{p.hidden=true;await c.run()};out.append(b)}};input.oninput=render;input.onkeydown=e=>{if(e.key==='Escape')p.hidden=true;if(e.key==='Enter')p.querySelector('.quick-results button')?.click()};window.CortexCommands={register,run:id=>commands.get(id)?.run(),list:()=>[...commands.values()].map(({id,label})=>({id,label})),open(){p.hidden=false;input.value='>';render();input.focus()}}}
function editors(){return monaco.editor.getEditors?.()||[]}function primary(){return editors()[0]}
function newUntitled(){const name=`Untitled-${++state.untitled}`,model=monaco.editor.createModel('','plaintext',monaco.Uri.parse(`untitled:${name}`));state.activeUntitled={name,model};primary()?.setModel(model);primary()?.focus();notify(`${name} created`)}
async function openSingleFile(){const path=await open({multiple:false,directory:false,title:'Open File'});if(!path)return;const s=String(path),parent=s.replace(/[\\/][^\\/]+$/,''),name=s.split(/[\\/]/).at(-1);await api()?.setWorkspace(parent);await api()?.openFile(name)}
async function saveUntitledAs(){if(!state.activeUntitled)return api()?.saveActive?.();const path=await save({title:'Save As'});if(!path)return;const s=String(path),parent=s.replace(/[\\/][^\\/]+$/,''),name=s.split(/[\\/]/).at(-1);await api()?.setWorkspace(parent);await invoke('write_workspace_file',{relative:name,text:state.activeUntitled.model.getValue()});await api()?.openFile(name);state.activeUntitled.model.dispose();state.activeUntitled=null;notify(`Saved ${name}`)}
function splitEditor(){const host=$('#editor-host'),model=primary()?.getModel();if(!host||state.splitEditor)return;if(!model)return notify('Open a file before splitting the editor','warning');host.classList.add('split');const n=document.createElement('div');n.className='editor';n.setAttribute('aria-label','Secondary Editor');host.append(n);state.splitEditor=monaco.editor.create(n,{model,theme:document.documentElement.dataset.theme==='light'?'vs':'vs-dark',automaticLayout:true,minimap:{enabled:false}})}function closeSplit(){state.splitEditor?.dispose();state.splitEditor=null;$('#editor-host')?.classList.remove('split');$('#editor-host .editor:nth-child(2)')?.remove()}
async function newTerminal(){const body=$('#panel-body');document.querySelector('[data-panel="terminal"]')?.click();const shell=document.createElement('section');shell.className='terminal-instance';const header=document.createElement('header'),title=document.createElement('button'),close=document.createElement('button'),host=document.createElement('div');title.textContent=`Terminal ${state.terminals.length+1}`;close.textContent='×';host.className='terminal-instance-host';header.append(title,close);shell.append(header,host);body.append(shell);const term=new Terminal({convertEol:true,fontSize:13}),fit=new FitAddon();term.loadAddon(fit);term.open(host);fit.fit();const started=await invoke('pty_start',{cols:term.cols,rows:term.rows}),item={id:started.id??started,term,shell,fit};state.terminals.push(item);state.activeTerminal=item;term.onData(data=>invoke('pty_write',{id:item.id,data}));const pump=async()=>{if(!state.terminals.includes(item))return;try{const chunk=await invoke('pty_read',{id:item.id});if(chunk)term.write(typeof chunk==='string'?chunk:(chunk.data||''));setTimeout(pump,40)}catch(e){notify(String(e),'error')}};pump();title.onclick=()=>{state.activeTerminal=item;term.focus()};close.onclick=async()=>{await invoke('pty_stop',{id:item.id}).catch(()=>{});term.dispose();shell.remove();state.terminals=state.terminals.filter(t=>t!==item)}}
function applyTheme(name){localStorage.setItem('cortex.theme',name);document.documentElement.dataset.theme=name;monaco.editor.setTheme(name==='light'?'vs':name==='high-contrast'?'hc-black':'vs-dark')}
function virtual(title,text){const body=$('#panel-body');body.innerHTML=`<h3>${esc(title)}</h3><pre>${esc(text)}</pre>`}function keybindings(){virtual('Keyboard Shortcuts',[['Ctrl/Cmd+Shift+P','Command Palette'],['Ctrl/Cmd+P','Quick Open'],['Ctrl/Cmd+N','New Untitled File'],['Ctrl/Cmd+O','Open File'],['Ctrl/Cmd+S','Save'],['Ctrl/Cmd+Shift+S','Save As'],['Ctrl/Cmd+\\','Split Editor'],['Ctrl/Cmd+`','Terminal'],['Ctrl/Cmd+Shift+`','New Terminal'],['F5','Start Debugging'],['F9','Toggle Breakpoint']].map(x=>x.join('    ')).join('\n'))}function settingsJson(){virtual('settings.json',JSON.stringify({theme:localStorage.getItem('cortex.theme')||'dark',...JSON.parse(localStorage.getItem('cortex.settings')||'{}')},null,2))}
function settings(){document.querySelector('.activity[data-view="settings"]')?.click();const side=$('#side-content');if(!side)return;side.insertAdjacentHTML('beforeend','<section class="freedom-settings"><h3>Workbench</h3><label>Theme<select id="freedom-theme"><option value="dark">Dark</option><option value="light">Light</option><option value="high-contrast">High Contrast</option></select></label><button id="keyboard-shortcuts">Keyboard Shortcuts</button><button id="settings-json">Open Settings JSON</button></section>');const t=$('#freedom-theme');t.value=localStorage.getItem('cortex.theme')||'dark';t.onchange=()=>applyTheme(t.value);$('#keyboard-shortcuts').onclick=keybindings;$('#settings-json').onclick=settingsJson}
async function quickOpen(){if(!api()?.getState?.().workspace)return openSingleFile();const files=await invoke('list_workspace_files');const q=prompt(`Quick Open (${files.length} files)\nType part of a path:`)?.trim().toLowerCase();if(!q)return;const hit=files.find(f=>f.toLowerCase()===q)||files.find(f=>f.toLowerCase().includes(q));if(hit)await api()?.openFile?.(hit);else notify('No matching workspace file','warning')}
function goLine(){const e=primary(),line=Number(prompt('Go to line:'));if(e&&line>0){e.setPosition({lineNumber:line,column:1});e.revealLineInCenter(line);e.focus()}}async function goSymbol(){const e=primary(),m=e?.getModel();if(!m)return;const provider=monaco.languages.getDocumentSymbols?.;const q=prompt('Go to symbol:')?.trim();if(!q)return;const hit=m.findMatches(q,false,false,false,null,true)[0];if(hit){e.setPosition(hit.range.getStartPosition());e.revealRangeInCenter(hit.range);e.focus()}}
async function workspaceReplace(){if(!api()?.getState?.().workspace)return notify('Open a workspace first','warning');const query=prompt('Replace in Files: find')??'';if(!query)return;const replacement=prompt(`Replace all occurrences of “${query}” with:`)??'';if(!confirm(`Replace all “${query}” occurrences across the workspace?`))return;const result=await invoke('replace_workspace',{query,replacement});notify(`Replaced ${result.replacements} occurrence(s) in ${result.filesChanged} file(s)`);window.dispatchEvent(new CustomEvent('cortex-workspace-changed',{detail:{path:api()?.getState?.().workspace}}))}
async function outline(){const model=primary()?.getModel();if(!model)return notify('Open a file first','warning');const symbols=[];for(const line of model.getLinesContent().map((text,index)=>({text,index}))){const m=/^\s*(?:export\s+)?(?:async\s+)?(?:class|function|const|let|var|interface|type|def|fn)\s+([A-Za-z_$][\w$]*)/.exec(line.text);if(m)symbols.push(`${line.index+1}: ${m[1]}`)}virtual('OUTLINE',symbols.join('\n')||'No symbols detected.')}
async function timeline(){if(!api()?.getState?.().workspace)return notify('Open a workspace first','warning');try{const history=await invoke('git_history',{limit:50});virtual('TIMELINE',typeof history==='string'?history:JSON.stringify(history,null,2))}catch(error){virtual('TIMELINE',`No Git timeline available.\n${error}`)}}
async function testing(){if(!api()?.getState?.().workspace)return notify('Open a workspace first','warning');const tasks=await invoke('discover_project_tasks');const tests=tasks.filter(t=>t.kind==='test'||/^test(?::|$)/i.test(t.name));const side=$('#side-content');$('#side-title').textContent='TESTING';side.replaceChildren();if(!tests.length){side.innerHTML='<div class="empty-side">No test tasks detected. Add a project test task or use your language test extension.</div>';return}for(const task of tests){const b=document.createElement('button');b.className='task-row';b.innerHTML=`<strong>▷ ${esc(task.name)}</strong><small>${esc(task.command)}</small>`;b.onclick=async()=>{b.disabled=true;b.firstElementChild.textContent=`◌ ${task.name}`;try{const r=await invoke('run_project_task',{name:task.name});virtual(`TEST: ${task.name}`,(r.stdout||'')+(r.stderr?`\n${r.stderr}`:''));b.firstElementChild.textContent=`${r.ok?'✓':'✗'} ${task.name}`}catch(e){b.firstElementChild.textContent=`✗ ${task.name}`;notify(String(e),'error')}finally{b.disabled=false}};side.append(b)}}
function toggleAI(){$('.assistant')?.classList.toggle('assistant-hidden')}
function installTestingActivity(){const settingsButton=document.querySelector('.activity[data-view="settings"]');if(!settingsButton||document.querySelector('.activity[data-view="testing"]'))return;const b=document.createElement('button');b.className='activity';b.dataset.view='testing';b.title='Testing';b.textContent='⚗';settingsButton.parentNode.insertBefore(b,document.querySelector('.activity-spacer')?.nextSibling||settingsButton);b.onclick=testing}
function installCommands(){register('workbench.action.showCommands','View: Show Command Palette',()=>window.CortexCommands.open());register('workbench.action.quickOpen','Go to File…',quickOpen);register('workbench.action.gotoLine','Go to Line…',goLine);register('workbench.action.gotoSymbol','Go to Symbol…',goSymbol);register('workbench.action.files.newUntitledFile','File: New Text File',newUntitled);register('workbench.action.files.openFile','File: Open File…',openSingleFile);register('workbench.action.files.openFolder','File: Open Folder…',()=>api()?.chooseWorkspace?.());register('workbench.action.files.save','File: Save',()=>state.activeUntitled?saveUntitledAs():api()?.saveActive?.());register('workbench.action.files.saveAs','File: Save As…',saveUntitledAs);register('workbench.action.findInFiles','Search: Find in Files',()=>api()?.renderSearch?.());register('workbench.action.replaceInFiles','Search: Replace in Files',workspaceReplace);register('workbench.action.splitEditorRight','View: Split Editor Right',splitEditor);register('workbench.action.closeEditorsInGroup','View: Close Secondary Editor',closeSplit,()=>!!state.splitEditor);register('workbench.action.terminal.new','Terminal: Create New Terminal',newTerminal);register('workbench.action.terminal.focus','Terminal: Focus Terminal',()=>state.activeTerminal?.term.focus());register('workbench.action.openSettings','Preferences: Open Settings',settings);register('workbench.action.openGlobalKeybindings','Preferences: Open Keyboard Shortcuts',keybindings);register('workbench.action.selectTheme','Preferences: Color Theme',()=>{const t=prompt('Theme: dark, light, high-contrast',localStorage.getItem('cortex.theme')||'dark');if(['dark','light','high-contrast'].includes(t))applyTheme(t)});register('workbench.action.showOutline','View: Show Outline',outline);register('workbench.action.showTimeline','View: Show Timeline',timeline);register('workbench.view.testing','View: Testing',testing);for(const [id,label,view] of [['workbench.view.explorer','View: Explorer','explorer'],['workbench.view.search','View: Search','search'],['workbench.view.scm','View: Source Control','source-control'],['workbench.view.debug','View: Run and Debug','run'],['workbench.view.extensions','View: Extensions','extensions']])register(id,label,()=>document.querySelector(`.activity[data-view="${view}"]`)?.click());register('workbench.action.toggleCortexAI','View: Toggle Cortex AI',toggleAI)}
function editorContextMenu(){document.addEventListener('contextmenu',e=>{if(!e.target.closest('.monaco-editor'))return;e.preventDefault();const choice=prompt('Editor action: cut, copy, paste, format, definition, references, rename, command')?.trim().toLowerCase();const ed=primary();if(choice==='cut')document.execCommand('cut');else if(choice==='copy')document.execCommand('copy');else if(choice==='paste')navigator.clipboard?.readText().then(text=>ed?.trigger('cortex','type',{text}));else if(choice==='format')ed?.getAction('editor.action.formatDocument')?.run();else if(choice==='definition')ed?.getAction('editor.action.revealDefinition')?.run();else if(choice==='references')ed?.getAction('editor.action.referenceSearch.trigger')?.run();else if(choice==='rename')ed?.getAction('editor.action.rename')?.run();else if(choice==='command')window.CortexCommands.open()})}
function keys(){window.addEventListener('keydown',e=>{const mod=e.ctrlKey||e.metaKey,key=e.key.toLowerCase();if(mod&&e.shiftKey&&key==='p'){e.preventDefault();window.CortexCommands.open()}else if(mod&&key==='p'){e.preventDefault();quickOpen()}else if(mod&&key==='n'){e.preventDefault();newUntitled()}else if(mod&&key==='o'){e.preventDefault();openSingleFile()}else if(mod&&e.shiftKey&&key==='s'){e.preventDefault();saveUntitledAs()}else if(mod&&key==='\\'){e.preventDefault();splitEditor()}else if(mod&&e.shiftKey&&e.key==='`'){e.preventDefault();newTerminal()}else if(e.key==='F1'){e.preventDefault();window.CortexCommands.open()}},true)}
applyTheme(localStorage.getItem('cortex.theme')||'dark');installPalette();installCommands();installTestingActivity();editorContextMenu();keys();notifications();window.CortexFreedom={commands,newUntitled,openSingleFile,saveUntitledAs,splitEditor,newTerminal,applyTheme,notify,quickOpen,workspaceReplace,testing,outline,timeline};
